package com.bridgework.sync.entity;

public enum PublicDataSourceType {
    KEPAD_RECRUITMENT,
    KEPAD_JOB_CATEGORY,
    KEPAD_STANDARD_WORKPLACE,
    KEPAD_SUPPORT_AGENCY,
    TRANSPORT_SUPPORT_CENTER,
    RAIL_WHEELCHAIR_LIFT,
    SEOUL_WHEELCHAIR_LIFT,
    VOCATIONAL_TRAINING,
    JOBSEEKER_COMPETENCY_PROGRAM
}
