package com.bridgework.sync.entity;

public enum PublicDataSourceType {
    KEPAD_RECRUITMENT,
    KEPAD_JOB_CATEGORY,
    KEPAD_STANDARD_WORKPLACE,
    KEPAD_SUPPORT_AGENCY,
    KORAIL_WEEK_PERSON_FACILITIES,
    SEOUL_TRANSPORT_WEAK_WHEELCHAIR_LIFT,
    TRANSPORT_SUPPORT_CENTER,
    RAIL_WHEELCHAIR_LIFT,
    RAIL_WHEELCHAIR_LIFT_MOVEMENT,
    SEOUL_WHEELCHAIR_LIFT,
    SEOUL_SUBWAY_ENTRANCE_LIFT,
    SEOUL_WALKING_NETWORK,
    NATIONWIDE_BUS_STOP,
    SEOUL_WHEELCHAIR_RAMP_STATUS,
    SEOUL_LOW_FLOOR_BUS_ROUTE_RETENTION,
    NATIONWIDE_TRAFFIC_LIGHT,
    NATIONWIDE_CROSSWALK,
    VOCATIONAL_TRAINING,
    JOBSEEKER_COMPETENCY_PROGRAM
}
