CREATE TABLE IF NOT EXISTS admin_dummy_user (
    id BIGSERIAL PRIMARY KEY,
    dummy_key VARCHAR(80) NOT NULL,
    display_name VARCHAR(120) NOT NULL,
    scenario_summary VARCHAR(500) NOT NULL,
    app_user_id BIGINT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_admin_dummy_user_key UNIQUE (dummy_key),
    CONSTRAINT uk_admin_dummy_user_app_user UNIQUE (app_user_id),
    CONSTRAINT fk_admin_dummy_user_app_user
        FOREIGN KEY (app_user_id)
        REFERENCES app_user (id)
        ON DELETE CASCADE,
    CONSTRAINT ck_admin_dummy_user_key_lower CHECK (dummy_key = lower(dummy_key))
);

CREATE TABLE IF NOT EXISTS admin_dummy_profile (
    id BIGSERIAL PRIMARY KEY,
    dummy_user_id BIGINT NOT NULL,
    profile_id BIGINT NOT NULL,
    profile_key VARCHAR(80) NOT NULL,
    profile_label VARCHAR(120) NOT NULL,
    scenario_summary VARCHAR(500) NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_admin_dummy_profile_case UNIQUE (dummy_user_id, profile_key),
    CONSTRAINT uk_admin_dummy_profile_profile UNIQUE (profile_id),
    CONSTRAINT fk_admin_dummy_profile_user
        FOREIGN KEY (dummy_user_id)
        REFERENCES admin_dummy_user (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_admin_dummy_profile_profile
        FOREIGN KEY (profile_id)
        REFERENCES onboarding_profile (id)
        ON DELETE CASCADE,
    CONSTRAINT ck_admin_dummy_profile_key_lower CHECK (profile_key = lower(profile_key))
);

CREATE TABLE IF NOT EXISTS admin_dummy_login_audit (
    id BIGSERIAL PRIMARY KEY,
    admin_user_id BIGINT NOT NULL,
    dummy_user_id BIGINT NOT NULL,
    issued_user_id BIGINT NOT NULL,
    request_ip VARCHAR(64),
    issued_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_admin_dummy_login_audit_user
        FOREIGN KEY (dummy_user_id)
        REFERENCES admin_dummy_user (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_admin_dummy_login_audit_issued_user
        FOREIGN KEY (issued_user_id)
        REFERENCES app_user (id)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_admin_dummy_user_active ON admin_dummy_user (is_active);
CREATE INDEX IF NOT EXISTS idx_admin_dummy_profile_user_sort ON admin_dummy_profile (dummy_user_id, sort_order, id);
CREATE INDEX IF NOT EXISTS idx_admin_dummy_login_audit_issued_at ON admin_dummy_login_audit (issued_at DESC);
CREATE INDEX IF NOT EXISTS idx_admin_dummy_login_audit_admin_user_id ON admin_dummy_login_audit (admin_user_id, issued_at DESC);

INSERT INTO app_user (
    provider,
    provider_user_id,
    email,
    role,
    signup_completed,
    created_at,
    updated_at
)
VALUES
    ('NAVER', 'dummy_case_office_user', 'dummy.office@bridgework.local', 'USER', TRUE, NOW(), NOW()),
    ('KAKAO', 'dummy_case_service_user', 'dummy.service@bridgework.local', 'USER', TRUE, NOW(), NOW()),
    ('NAVER', 'dummy_case_mobility_user', 'dummy.mobility@bridgework.local', 'USER', TRUE, NOW(), NOW())
ON CONFLICT (provider, provider_user_id)
    DO UPDATE SET
        email = EXCLUDED.email,
        role = 'USER',
        signup_completed = TRUE,
        updated_at = NOW();

INSERT INTO onboarding_profile (
    user_id,
    is_default,
    desired_job,
    commute_range,
    preferred_work_environments_json,
    avoided_work_environments_json,
    required_supports_json,
    disability_type,
    career_summary,
    education_summary,
    employment_type_summary,
    full_name,
    contact_phone,
    contact_email,
    birth_date,
    age_group,
    residence_region,
    detail_address,
    emergency_contact,
    profile_image_url,
    highest_education,
    graduation_status,
    major_career,
    career_detail,
    project_experience,
    career_gap_reason,
    target_job,
    skills_json,
    certifications_json,
    portfolio_url,
    awards,
    trainings,
    disability_yn,
    disability_severity,
    disability_registered_yn,
    disability_description,
    assistive_devices,
    work_support_requirements,
    work_availability,
    work_types_json,
    expected_salary,
    work_time_preference,
    remote_available_yn,
    mobility_range,
    self_introduction,
    motivation,
    job_fit_description,
    career_goal,
    strengths_weaknesses,
    military_service,
    patriotic_veteran_yn,
    referrer,
    sns_url,
    ai_job_tags_json,
    ai_environment_tags_json,
    ai_support_tags_json,
    created_at,
    updated_at
)
VALUES
    (
        (SELECT id FROM app_user WHERE provider = 'NAVER' AND provider_user_id = 'dummy_case_office_user'),
        TRUE,
        '사무 보조',
        '대중교통 40분 이내',
        '["저소음 환경","좌식 업무"]',
        '[]',
        '["업무 매뉴얼 제공"]',
        '지체장애',
        '신입',
        '고등학교 졸업',
        '정규직/계약직',
        '김서연(더미-사무신입)',
        '010-2200-1101',
        'dummy.office.1@bridgework.local',
        DATE '1999-03-12',
        '20대',
        '서울',
        '서울시 동작구 상도동',
        NULL,
        NULL,
        '고졸',
        '졸업',
        '학교 행정실 보조 아르바이트',
        NULL,
        NULL,
        NULL,
        '사무 보조',
        '["문서작성","엑셀"]',
        '[]',
        NULL,
        NULL,
        NULL,
        TRUE,
        '경증',
        TRUE,
        '장시간 서있는 업무가 어렵습니다.',
        NULL,
        '출퇴근 동선이 단순한 근무지 선호',
        '즉시',
        '["정규직","계약직"]',
        NULL,
        NULL,
        FALSE,
        '10km',
        '꼼꼼하고 반복 업무에 강점이 있습니다.',
        '장기 근속 가능한 사무직을 희망합니다.',
        NULL,
        'OA 기반 업무 전문성 확보',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        '["사무"]',
        '["좌식","저소음"]',
        '["매뉴얼"]',
        NOW(),
        NOW()
    ),
    (
        (SELECT id FROM app_user WHERE provider = 'NAVER' AND provider_user_id = 'dummy_case_office_user'),
        FALSE,
        '총무/경영지원',
        '대중교통 60분 이내',
        '["유연근무","재택 일부 가능"]',
        '["고객 응대 전담"]',
        '["업무 보조기기 협의"]',
        '지체장애',
        '행정지원 1년',
        '전문학사',
        '계약직/재택',
        '김서연(더미-사무확장)',
        '010-2200-1102',
        'dummy.office.2@bridgework.local',
        DATE '1999-03-12',
        '20대',
        '경기',
        '경기도 안양시 동안구',
        '010-0000-1102',
        NULL,
        '전문대졸',
        '졸업',
        '행정지원 및 구매요청 처리',
        '월간 비용 정산 및 문서 결재 보조',
        '업무 효율화 템플릿 제작',
        NULL,
        '총무',
        '["엑셀","파워포인트","문서관리"]',
        '["컴퓨터활용능력 2급"]',
        'https://portfolio.example.com/dummy-office',
        '교내 행정 아이디어 공모전 장려상',
        '사무자동화 과정 수료',
        TRUE,
        '경증',
        TRUE,
        '계단 이동이 많은 환경은 어렵습니다.',
        '휴대용 보조기기',
        '유연한 휴게시간',
        '1개월 내',
        '["계약직","재택/원격"]',
        '3200만원',
        '주간',
        TRUE,
        '15km',
        '업무 프로세스 개선 제안을 적극적으로 수행합니다.',
        '조직 운영을 지원하는 백오피스 전문가가 되고 싶습니다.',
        '정리 능력과 협업 커뮤니케이션이 강점입니다.',
        '경영지원 직무 스페셜리스트',
        '완벽주의 성향으로 속도가 늦을 때가 있습니다.',
        NULL,
        FALSE,
        '커뮤니티 추천',
        'https://linkedin.com/in/dummy-office',
        '["총무","경영지원"]',
        '["유연근무","재택"]',
        '["휴게시간","보조기기"]',
        NOW(),
        NOW()
    ),
    (
        (SELECT id FROM app_user WHERE provider = 'KAKAO' AND provider_user_id = 'dummy_case_service_user'),
        TRUE,
        '고객상담',
        '대중교통 50분 이내',
        '["콜센터","표준화 스크립트"]',
        '["야간 교대"]',
        '["업무 적응 코칭"]',
        '청각장애',
        '고객응대 4년',
        '대학교 졸업',
        '정규직',
        '박지훈(더미-상담기본)',
        '010-3300-2201',
        'dummy.service.1@bridgework.local',
        DATE '1992-08-02',
        '30대',
        '인천',
        '인천시 남동구 논현동',
        NULL,
        NULL,
        '대졸',
        '졸업',
        '통신사 인바운드 상담',
        '불만 고객 대응 및 이탈 방지',
        NULL,
        '육아로 인한 1년 공백',
        '고객상담',
        '["고객응대","CRM","문제해결"]',
        '["CS Leaders"]',
        NULL,
        NULL,
        '장애 인식 개선 교육 수료',
        TRUE,
        '중등도',
        TRUE,
        '잡음이 큰 환경에서는 의사소통 정확도가 떨어집니다.',
        '보청기',
        '화상/텍스트 병행 커뮤니케이션',
        '즉시',
        '["정규직"]',
        '3400만원',
        '주간',
        FALSE,
        '20km',
        '고객 감정 완화와 문제 해결에 자신 있습니다.',
        '장기적으로 상담 품질관리 리더를 목표로 합니다.',
        '상담 KPI 분석 경험 보유',
        '고객경험 관리자',
        '높은 공감 성향으로 감정 소모가 큽니다.',
        NULL,
        FALSE,
        NULL,
        NULL,
        '["상담","고객관리"]',
        '["저소음"]',
        '["텍스트커뮤니케이션"]',
        NOW(),
        NOW()
    ),
    (
        (SELECT id FROM app_user WHERE provider = 'KAKAO' AND provider_user_id = 'dummy_case_service_user'),
        FALSE,
        '고객지원 QA',
        '대중교통 70분 이내',
        '["품질 모니터링","하이브리드"]',
        '["고강도 실시간 콜"]',
        '["문서 기반 협업"]',
        '청각장애',
        '상담 QA 2년',
        '대학교 졸업',
        '정규직/재택',
        '박지훈(더미-QA전환)',
        '010-3300-2202',
        'dummy.service.2@bridgework.local',
        DATE '1992-08-02',
        '30대',
        '경기',
        '경기도 부천시 원미구',
        '010-0000-2202',
        NULL,
        '대졸',
        '졸업',
        '상담 모니터링 및 피드백',
        '상담 스크립트 품질 기준 수립',
        'VOC 분류 자동화 프로젝트 참여',
        NULL,
        '고객지원 QA',
        '["품질관리","데이터분석","커뮤니케이션"]',
        '["SQLD"]',
        'https://portfolio.example.com/dummy-service',
        '우수 상담사 표창',
        '데이터 분석 부트캠프 수료',
        TRUE,
        '중등도',
        TRUE,
        '영상 자막/문서 중심 커뮤니케이션 선호',
        '보청기',
        '회의 자막 지원',
        '2개월 내',
        '["정규직","재택/원격"]',
        '3800만원',
        '주간',
        TRUE,
        '25km',
        '고객 불편 원인을 데이터로 분석하는 것을 좋아합니다.',
        '품질 체계를 설계하는 역할로 성장하고 싶습니다.',
        '문서화와 기준 수립 능력',
        '고객지원 품질 전략가',
        '새 업무 적응 초기에 질문이 많은 편입니다.',
        NULL,
        FALSE,
        '지인 추천',
        'https://github.com/dummy-service',
        '["QA","품질관리"]',
        '["문서협업","하이브리드"]',
        '["자막","문서회의"]',
        NOW(),
        NOW()
    ),
    (
        (SELECT id FROM app_user WHERE provider = 'NAVER' AND provider_user_id = 'dummy_case_mobility_user'),
        TRUE,
        'IT 헬프데스크',
        '대중교통 30분 이내',
        '["사내 지원센터","고정 좌석"]',
        '["현장 순회 업무"]',
        '["건물 접근성 확인"]',
        '지체장애',
        '사내 IT지원 3년',
        '전문학사',
        '정규직',
        '이민아(더미-접근성중점)',
        '010-4400-3301',
        'dummy.mobility.1@bridgework.local',
        DATE '1995-11-24',
        '30대',
        '서울',
        '서울시 강동구 천호동',
        NULL,
        NULL,
        '전문대졸',
        '졸업',
        '사내 장비 세팅 및 계정 권한 관리',
        '장애 대응 지원 환경 체크리스트 운영',
        NULL,
        NULL,
        'IT 지원',
        '["윈도우관리","헬프데스크","장비세팅"]',
        '["정보처리기능사"]',
        NULL,
        NULL,
        '보조공학 교육 수료',
        TRUE,
        '중증',
        TRUE,
        '휠체어 이용으로 경사로/엘리베이터 접근이 중요합니다.',
        '전동휠체어',
        '출입구/사내 이동 동선 접근성 확보',
        '즉시',
        '["정규직"]',
        '3600만원',
        '주간',
        FALSE,
        '8km',
        '문제 상황을 차분히 파악하고 해결합니다.',
        '접근성 친화 IT 운영 담당자로 성장하고 싶습니다.',
        '현장 대응 및 사용자 커뮤니케이션 능력',
        'IT 운영 매니저',
        '체력 소모가 큰 이동 업무는 제한이 있습니다.',
        NULL,
        FALSE,
        NULL,
        NULL,
        '["IT지원","헬프데스크"]',
        '["고정좌석","접근성"]',
        '["접근성확보"]',
        NOW(),
        NOW()
    ),
    (
        (SELECT id FROM app_user WHERE provider = 'NAVER' AND provider_user_id = 'dummy_case_mobility_user'),
        FALSE,
        '정보보안 운영',
        '대중교통 45분 이내',
        '["모니터링 센터","하이브리드"]',
        '["야간 순찰"]',
        '["긴급 상황 시 동선 지원"]',
        '지체장애',
        '보안관제 보조 2년',
        '대학교 졸업',
        '정규직/계약직',
        '이민아(더미-보안운영)',
        '010-4400-3302',
        'dummy.mobility.2@bridgework.local',
        DATE '1995-11-24',
        '30대',
        '서울',
        '서울시 송파구 잠실동',
        '010-0000-3302',
        NULL,
        '대졸',
        '졸업',
        '보안 이벤트 대응 및 리포트 작성',
        '접근권한 이상징후 모니터링',
        '내부 보안 교육 콘텐츠 제작',
        NULL,
        '보안 운영',
        '["SIEM","로그분석","리포팅"]',
        '["정보보안기사 필기"]',
        'https://portfolio.example.com/dummy-mobility',
        NULL,
        '보안관제 실무 과정 수료',
        TRUE,
        '중증',
        TRUE,
        '이동 동선과 좌석 접근이 안정적이면 집중도가 높습니다.',
        '전동휠체어',
        '야간 비상동선 대체 지원',
        '1개월 내',
        '["정규직","계약직"]',
        '4000만원',
        '주간',
        TRUE,
        '12km',
        '장애 대응 관점에서도 안정적인 운영 체계를 만들고 싶습니다.',
        '접근성과 보안을 함께 고려하는 운영 담당자가 목표입니다.',
        '위기 대응 체크리스트 설계 경험',
        '보안 운영 스페셜리스트',
        '새로운 툴 적응에 초기 학습 시간이 필요합니다.',
        NULL,
        FALSE,
        '채용 플랫폼',
        'https://blog.example.com/dummy-mobility',
        '["보안","운영"]',
        '["하이브리드","모니터링"]',
        '["동선지원","접근성좌석"]',
        NOW(),
        NOW()
    );

INSERT INTO admin_dummy_user (
    dummy_key,
    display_name,
    scenario_summary,
    app_user_id,
    is_active,
    created_at,
    updated_at
)
VALUES
    (
        'case-office-rookie',
        '사무지원 신입형',
        '필수 중심 입력과 선택 확장 입력을 함께 검증할 수 있는 사무 직군 케이스',
        (SELECT id FROM app_user WHERE provider = 'NAVER' AND provider_user_id = 'dummy_case_office_user'),
        TRUE,
        NOW(),
        NOW()
    ),
    (
        'case-service-transition',
        '고객지원 경력전환형',
        '상담 경력 기반으로 QA/품질 직무 전환 시나리오를 검증할 수 있는 케이스',
        (SELECT id FROM app_user WHERE provider = 'KAKAO' AND provider_user_id = 'dummy_case_service_user'),
        TRUE,
        NOW(),
        NOW()
    ),
    (
        'case-mobility-support',
        '접근성 중점형',
        '이동 보조/접근성 요구사항이 큰 사용자 시나리오를 검증할 수 있는 케이스',
        (SELECT id FROM app_user WHERE provider = 'NAVER' AND provider_user_id = 'dummy_case_mobility_user'),
        TRUE,
        NOW(),
        NOW()
    )
ON CONFLICT (dummy_key)
    DO UPDATE SET
        display_name = EXCLUDED.display_name,
        scenario_summary = EXCLUDED.scenario_summary,
        app_user_id = EXCLUDED.app_user_id,
        is_active = EXCLUDED.is_active,
        updated_at = NOW();

INSERT INTO admin_dummy_profile (
    dummy_user_id,
    profile_id,
    profile_key,
    profile_label,
    scenario_summary,
    sort_order,
    created_at,
    updated_at
)
VALUES
    (
        (SELECT id FROM admin_dummy_user WHERE dummy_key = 'case-office-rookie'),
        (SELECT id FROM onboarding_profile WHERE full_name = '김서연(더미-사무신입)' ORDER BY id DESC LIMIT 1),
        'office-default',
        '사무신입 기본형',
        '필수 입력 위주 기본 프로필',
        1,
        NOW(),
        NOW()
    ),
    (
        (SELECT id FROM admin_dummy_user WHERE dummy_key = 'case-office-rookie'),
        (SELECT id FROM onboarding_profile WHERE full_name = '김서연(더미-사무확장)' ORDER BY id DESC LIMIT 1),
        'office-extended',
        '사무신입 확장형',
        '선택 입력을 풍부하게 포함한 확장 프로필',
        2,
        NOW(),
        NOW()
    ),
    (
        (SELECT id FROM admin_dummy_user WHERE dummy_key = 'case-service-transition'),
        (SELECT id FROM onboarding_profile WHERE full_name = '박지훈(더미-상담기본)' ORDER BY id DESC LIMIT 1),
        'service-default',
        '상담경력 기본형',
        '고객응대 경력 기반 기본 프로필',
        1,
        NOW(),
        NOW()
    ),
    (
        (SELECT id FROM admin_dummy_user WHERE dummy_key = 'case-service-transition'),
        (SELECT id FROM onboarding_profile WHERE full_name = '박지훈(더미-QA전환)' ORDER BY id DESC LIMIT 1),
        'service-qa',
        'QA 전환형',
        '품질관리 전환 시나리오 중심 프로필',
        2,
        NOW(),
        NOW()
    ),
    (
        (SELECT id FROM admin_dummy_user WHERE dummy_key = 'case-mobility-support'),
        (SELECT id FROM onboarding_profile WHERE full_name = '이민아(더미-접근성중점)' ORDER BY id DESC LIMIT 1),
        'mobility-default',
        '접근성 중점 기본형',
        '접근성 요구사항 중심 기본 프로필',
        1,
        NOW(),
        NOW()
    ),
    (
        (SELECT id FROM admin_dummy_user WHERE dummy_key = 'case-mobility-support'),
        (SELECT id FROM onboarding_profile WHERE full_name = '이민아(더미-보안운영)' ORDER BY id DESC LIMIT 1),
        'mobility-security',
        '접근성 + 보안운영형',
        '보안 운영 직무 확장 시나리오 프로필',
        2,
        NOW(),
        NOW()
    )
ON CONFLICT (dummy_user_id, profile_key)
    DO UPDATE SET
        profile_id = EXCLUDED.profile_id,
        profile_label = EXCLUDED.profile_label,
        scenario_summary = EXCLUDED.scenario_summary,
        sort_order = EXCLUDED.sort_order,
        updated_at = NOW();
