CREATE TABLE IF NOT EXISTS pd_kepad_recruitment (
    id BIGSERIAL PRIMARY KEY,
    external_id VARCHAR(128) NOT NULL UNIQUE,
    payload_hash CHAR(64) NOT NULL,
    raw_fetched_at TIMESTAMP WITH TIME ZONE NOT NULL,
    buspla_name TEXT,
    cntct_no TEXT,
    comp_addr TEXT,
    emp_type TEXT,
    enter_type TEXT,
    env_both_hands TEXT,
    env_eyesight TEXT,
    env_lstn_talk TEXT,
    job_nm TEXT,
    offerreg_dt TEXT,
    reg_dt TEXT,
    regagn_name TEXT,
    req_career TEXT,
    req_educ TEXT,
    rno TEXT,
    rnum TEXT,
    salary TEXT,
    salary_type TEXT,
    term_date TEXT,
    env_hand_work TEXT,
    env_lift_power TEXT,
    env_stnd_walk TEXT,
    req_major TEXT,
    req_licens TEXT,
    geo_original_address TEXT,
    geo_matched_address TEXT,
    geo_latitude DOUBLE PRECISION,
    geo_longitude DOUBLE PRECISION,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_pd_kepad_recruitment_updated_at ON pd_kepad_recruitment (updated_at DESC);

CREATE TABLE IF NOT EXISTS pd_kepad_job_category (
    id BIGSERIAL PRIMARY KEY,
    external_id VARCHAR(128) NOT NULL UNIQUE,
    payload_hash CHAR(64) NOT NULL,
    raw_fetched_at TIMESTAMP WITH TIME ZONE NOT NULL,
    job_cd TEXT,
    job_cd_level TEXT,
    job_cd_nm TEXT,
    rnum TEXT,
    job_task TEXT,
    notice_cn TEXT,
    simlr_job TEXT,
    sprd_ockcls_yn TEXT,
    jobdevtip_cn TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS pd_kepad_standard_workplace (
    id BIGSERIAL PRIMARY KEY,
    external_id VARCHAR(128) NOT NULL UNIQUE,
    payload_hash CHAR(64) NOT NULL,
    raw_fetched_at TIMESTAMP WITH TIME ZONE NOT NULL,
    address TEXT,
    auth_date TEXT,
    comp_auth_id TEXT,
    comp_biz_no TEXT,
    comp_name TEXT,
    comp_reg_no TEXT,
    comp_tel TEXT,
    comp_type_nm TEXT,
    president_name TEXT,
    product TEXT,
    rnum TEXT,
    comp_mgr_no TEXT,
    cancel_date TEXT,
    comp_cert TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS pd_kepad_support_agency (
    id BIGSERIAL PRIMARY KEY,
    external_id VARCHAR(128) NOT NULL UNIQUE,
    payload_hash CHAR(64) NOT NULL,
    raw_fetched_at TIMESTAMP WITH TIME ZONE NOT NULL,
    exc_instn TEXT,
    exc_instn_addr TEXT,
    exc_instn_fxno TEXT,
    exc_instn_nm TEXT,
    exc_instn_telno TEXT,
    rnum TEXT,
    geo_original_address TEXT,
    geo_matched_address TEXT,
    geo_latitude DOUBLE PRECISION,
    geo_longitude DOUBLE PRECISION,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS pd_korail_week_person_facilities (
    id BIGSERIAL PRIMARY KEY,
    external_id VARCHAR(128) NOT NULL UNIQUE,
    payload_hash CHAR(64) NOT NULL,
    raw_fetched_at TIMESTAMP WITH TIME ZONE NOT NULL,
    pwdbs_slwy_estnc TEXT,
    pwdbs_tolt_estnc TEXT,
    stn_cd TEXT,
    stn_nm TEXT,
    whlch_liftt_cnt TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS pd_seoul_transport_weak_wheelchair_lift (
    id BIGSERIAL PRIMARY KEY,
    external_id VARCHAR(128) NOT NULL UNIQUE,
    payload_hash CHAR(64) NOT NULL,
    raw_fetched_at TIMESTAMP WITH TIME ZONE NOT NULL,
    fclt_no TEXT,
    fclt_nm TEXT,
    line_nm TEXT,
    stn_cd TEXT,
    stn_nm TEXT,
    stn_no TEXT,
    crtr_ymd TEXT,
    elvtr_sn TEXT,
    mng_no TEXT,
    vcnt_entrc_no TEXT,
    bgng_flr_grnd_udgd_se TEXT,
    bgng_flr TEXT,
    bgng_flr_dtl_pstn TEXT,
    end_flr_grnd_udgd_se TEXT,
    end_flr TEXT,
    end_flr_dtl_pstn TEXT,
    elvtr_len TEXT,
    elvtr_wdth_bt TEXT,
    limit_wht TEXT,
    oprtng_situ TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS pd_transport_support_center (
    id BIGSERIAL PRIMARY KEY,
    external_id VARCHAR(128) NOT NULL UNIQUE,
    payload_hash CHAR(64) NOT NULL,
    raw_fetched_at TIMESTAMP WITH TIME ZONE NOT NULL,
    tfcwker_mvmn_cnter_nm TEXT,
    rdnmadr TEXT,
    lnmadr TEXT,
    latitude TEXT,
    longitude TEXT,
    car_hold_co TEXT,
    car_hold_knd TEXT,
    slope_vhcle_co TEXT,
    lift_vhcle_co TEXT,
    rcept_phone_number TEXT,
    rcept_itnadr TEXT,
    app_svc_nm TEXT,
    weekday_rcept_open_hhmm TEXT,
    weekday_rcept_colse_hhmm TEXT,
    wkend_rcept_open_hhmm TEXT,
    wkend_rcept_close_hhmm TEXT,
    weekday_oper_open_hhmm TEXT,
    weekday_oper_colse_hhmm TEXT,
    wkend_oper_open_hhmm TEXT,
    wkend_oper_close_hhmm TEXT,
    beffat_resve_pd TEXT,
    use_lmtt TEXT,
    inside_oprat_area TEXT,
    outside_oprat_area TEXT,
    use_trget TEXT,
    use_charge TEXT,
    institution_nm TEXT,
    phone_number TEXT,
    reference_date TEXT,
    instt_code TEXT,
    instt_nm TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS pd_rail_wheelchair_lift (
    id BIGSERIAL PRIMARY KEY,
    external_id VARCHAR(128) NOT NULL UNIQUE,
    payload_hash CHAR(64) NOT NULL,
    raw_fetched_at TIMESTAMP WITH TIME ZONE NOT NULL,
    rail_opr_istt_cd TEXT,
    ln_cd TEXT,
    stin_cd TEXT,
    exit_no TEXT,
    dtl_loc TEXT,
    grnd_dv_nm_fr TEXT,
    run_stin_flor_fr TEXT,
    grnd_dv_nm_to TEXT,
    run_stin_flor_to TEXT,
    len TEXT,
    wd TEXT,
    bnd_wgt TEXT,
    ln_nm TEXT,
    stin_nm TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS pd_rail_wheelchair_lift_movement (
    id BIGSERIAL PRIMARY KEY,
    external_id VARCHAR(128) NOT NULL UNIQUE,
    payload_hash CHAR(64) NOT NULL,
    raw_fetched_at TIMESTAMP WITH TIME ZONE NOT NULL,
    rail_opr_istt_cd TEXT,
    ln_cd TEXT,
    stin_cd TEXT,
    mv_path_mg_no TEXT,
    mv_path_dv_cd TEXT,
    mv_path_dv_nm TEXT,
    mv_tp_ordr TEXT,
    mv_dst TEXT,
    mv_cont_dtl TEXT,
    ln_nm TEXT,
    stin_nm TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS pd_seoul_wheelchair_lift (
    id BIGSERIAL PRIMARY KEY,
    external_id VARCHAR(128) NOT NULL UNIQUE,
    payload_hash CHAR(64) NOT NULL,
    raw_fetched_at TIMESTAMP WITH TIME ZONE NOT NULL,
    entrance_no TEXT,
    management_no TEXT,
    length TEXT,
    data_base_date TEXT,
    elevator_serial_no TEXT,
    start_floor_detail_location TEXT,
    start_floor_operation_station_floor TEXT,
    start_floor_ground_basement TEXT,
    station_name TEXT,
    serial_number TEXT,
    end_floor_detail_location TEXT,
    end_floor_operation_station_floor TEXT,
    end_floor_ground_basement TEXT,
    width TEXT,
    weight_limit TEXT,
    line_name TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS pd_seoul_subway_entrance_lift (
    id BIGSERIAL PRIMARY KEY,
    external_id VARCHAR(128) NOT NULL UNIQUE,
    payload_hash CHAR(64) NOT NULL,
    raw_fetched_at TIMESTAMP WITH TIME ZONE NOT NULL,
    node_type TEXT,
    node_wkt TEXT,
    node_id TEXT,
    node_type_cd TEXT,
    sgg_cd TEXT,
    sgg_nm TEXT,
    emd_cd TEXT,
    emd_nm TEXT,
    sbwy_stn_cd TEXT,
    sbwy_stn_nm TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS pd_seoul_walking_network (
    id BIGSERIAL PRIMARY KEY,
    external_id VARCHAR(128) NOT NULL UNIQUE,
    payload_hash CHAR(64) NOT NULL,
    raw_fetched_at TIMESTAMP WITH TIME ZONE NOT NULL,
    node_type TEXT,
    node_wkt TEXT,
    node_id TEXT,
    node_type_cd TEXT,
    lnkg_wkt TEXT,
    lnkg_id TEXT,
    lnkg_type_cd TEXT,
    bgng_lnkg_id TEXT,
    end_lnkg_id TEXT,
    lnkg_len TEXT,
    sgg_cd TEXT,
    sgg_nm TEXT,
    emd_cd TEXT,
    emd_nm TEXT,
    expn_car_rd TEXT,
    sbwy_ntw TEXT,
    brg TEXT,
    tnl TEXT,
    ovrp TEXT,
    crswk TEXT,
    park TEXT,
    bldg TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS pd_nationwide_bus_stop (
    id BIGSERIAL PRIMARY KEY,
    external_id VARCHAR(128) NOT NULL UNIQUE,
    payload_hash CHAR(64) NOT NULL,
    raw_fetched_at TIMESTAMP WITH TIME ZONE NOT NULL,
    longitude TEXT,
    admin_city_name TEXT,
    city_name TEXT,
    city_code TEXT,
    mobile_short_no TEXT,
    latitude TEXT,
    stop_name TEXT,
    stop_id TEXT,
    collected_at TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS pd_seoul_wheelchair_ramp_status (
    id BIGSERIAL PRIMARY KEY,
    external_id VARCHAR(128) NOT NULL UNIQUE,
    payload_hash CHAR(64) NOT NULL,
    raw_fetched_at TIMESTAMP WITH TIME ZONE NOT NULL,
    line_name TEXT,
    station_name TEXT,
    division TEXT,
    location TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS pd_seoul_low_floor_bus_route_retention (
    id BIGSERIAL PRIMARY KEY,
    external_id VARCHAR(128) NOT NULL UNIQUE,
    payload_hash CHAR(64) NOT NULL,
    raw_fetched_at TIMESTAMP WITH TIME ZONE NOT NULL,
    route_no TEXT,
    authorized_count TEXT,
    low_floor_bus_count TEXT,
    low_floor_retention_rate TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS pd_nationwide_traffic_light (
    id BIGSERIAL PRIMARY KEY,
    external_id VARCHAR(128) NOT NULL UNIQUE,
    payload_hash CHAR(64) NOT NULL,
    raw_fetched_at TIMESTAMP WITH TIME ZONE NOT NULL,
    ctprvn_nm TEXT,
    signgu_nm TEXT,
    road_knd TEXT,
    road_route_no TEXT,
    road_route_nm TEXT,
    road_route_drc TEXT,
    rdnmadr TEXT,
    lnmadr TEXT,
    latitude TEXT,
    longitude TEXT,
    sgngnr_instl_mthd TEXT,
    road_type TEXT,
    prior_road_yn TEXT,
    tfclght_manage_no TEXT,
    tfclght_se TEXT,
    tfclght_color_knd TEXT,
    sgnasp_mthd TEXT,
    sgnasp_ordr TEXT,
    sgnasp_time TEXT,
    sot_knd TEXT,
    signl_ctrl_mthd TEXT,
    signl_time_mthd_type TEXT,
    opratn_yn TEXT,
    flashing_light_open_hhmm TEXT,
    flashing_light_close_hhmm TEXT,
    fnctng_sgngnr_yn TEXT,
    remndr_idct_yn TEXT,
    sond_sgngnr_yn TEXT,
    drcbrd_sn TEXT,
    institution_nm TEXT,
    phone_number TEXT,
    reference_date TEXT,
    instt_code TEXT,
    instt_nm TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS pd_nationwide_crosswalk (
    id BIGSERIAL PRIMARY KEY,
    external_id VARCHAR(128) NOT NULL UNIQUE,
    payload_hash CHAR(64) NOT NULL,
    raw_fetched_at TIMESTAMP WITH TIME ZONE NOT NULL,
    ctprvn_nm TEXT,
    signgu_nm TEXT,
    road_nm TEXT,
    rdnmadr TEXT,
    lnmadr TEXT,
    crslk_manage_no TEXT,
    crslk_knd TEXT,
    bcycl_crslk_cmbnat_yn TEXT,
    highland_yn TEXT,
    latitude TEXT,
    longitude TEXT,
    cartrk_co TEXT,
    bt TEXT,
    et TEXT,
    tfclght_yn TEXT,
    fnctng_sgngnr_yn TEXT,
    sond_sgngnr_yn TEXT,
    green_sgngnr_time TEXT,
    red_sgngnr_time TEXT,
    tfcilnd_yn TEXT,
    ftpth_lower_yn TEXT,
    brll_blck_yn TEXT,
    cnctr_lght_fclty_yn TEXT,
    institution_nm TEXT,
    phone_number TEXT,
    reference_date TEXT,
    instt_code TEXT,
    instt_nm TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS pd_vocational_training (
    id BIGSERIAL PRIMARY KEY,
    external_id VARCHAR(128) NOT NULL UNIQUE,
    payload_hash CHAR(64) NOT NULL,
    raw_fetched_at TIMESTAMP WITH TIME ZONE NOT NULL,
    address TEXT,
    certificate TEXT,
    contents TEXT,
    course_man TEXT,
    ei_empl_cnt3 TEXT,
    ei_empl_cnt3_gt10 TEXT,
    ei_empl_rate3 TEXT,
    ei_empl_rate6 TEXT,
    grade TEXT,
    inst_cd TEXT,
    ncs_cd TEXT,
    real_man TEXT,
    reg_course_man TEXT,
    stdg_scor TEXT,
    sub_title TEXT,
    sub_title_link TEXT,
    tel_no TEXT,
    title TEXT,
    title_icon TEXT,
    title_link TEXT,
    tra_end_date TEXT,
    tra_start_date TEXT,
    train_target TEXT,
    train_target_cd TEXT,
    trainst_cst_id TEXT,
    trng_area_cd TEXT,
    trpr_degr TEXT,
    trpr_id TEXT,
    wkend_se TEXT,
    yard_man TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS pd_jobseeker_competency_program (
    id BIGSERIAL PRIMARY KEY,
    external_id VARCHAR(128) NOT NULL UNIQUE,
    payload_hash CHAR(64) NOT NULL,
    raw_fetched_at TIMESTAMP WITH TIME ZONE NOT NULL,
    org_nm TEXT,
    pgm_nm TEXT,
    pgm_sub_nm TEXT,
    pgm_target TEXT,
    pgm_stdt TEXT,
    pgm_endt TEXT,
    open_time_clcd TEXT,
    open_time TEXT,
    operation_time TEXT,
    open_plc_cont TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);
